;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "github-slash-commands-skill")
(def path ".")
(def version "0.1.37")
(def tag "0.1.37")
(def generated-at "2020-09-03T18:40:48Z")
