;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "git-chatops-skill")
(def path ".")
(def version "0.1.24")
(def tag "0.1.24")
(def generated-at "2020-05-26T21:14:45Z")
